import {Temporal} from '@js-temporal/polyfill';import type {Command} from '../commands/schema';import type {MarketDataProvider} from '../data/marketData';import type {Overlay,Resolution} from './types';
const id=()=>crypto.randomUUID(); const iso=(t:number)=>new Date(t*1000).toISOString();
export class CommandResolver{constructor(private data:MarketDataProvider){} resolve(command:Command,symbol:string):Resolution{const bars=this.data.bars(symbol),ctx=bars.at(-1)!;
 const line=(semanticKey:string,label:string,b=ctx):Resolution=>{const o:Overlay={id:id(),semanticKey,kind:'line',label,price:b.open,sourceTime:b.time};return{overlays:[o],message:`${label}: ${b.open.toFixed(2)} from ${iso(b.time)}`}};
 const nyDate=(b:typeof ctx)=>Temporal.Instant.fromEpochMilliseconds(b.time*1000).toZonedDateTimeISO('America/New_York').toPlainDate();
 const sessions=new Map<string,typeof bars>();for(const b of bars){const d=nyDate(b).toString();sessions.set(d,[...(sessions.get(d)||[]),b])}const dates=[...sessions.keys()].sort();const contextDate=nyDate(ctx).toString();
 if(command.type==='ADD_MONDAY_OPEN'){let target=Temporal.PlainDate.from(contextDate);target=target.subtract({days:target.dayOfWeek-1+(command.week==='previous'?7:0)});let found;for(let n=0;n<7&&!found;n++)found=sessions.get(target.add({days:n}).toString())?.find(b=>Temporal.Instant.fromEpochMilliseconds(b.time*1000).toZonedDateTimeISO('America/New_York').hour===this.data.meta(symbol).sessionHour);if(!found)throw Error('DATA_UNAVAILABLE');const weekday=nyDate(found).toLocaleString('en-US',{weekday:'long'});return line(`monday-open:${target}`,`${weekday} weekly open`,found)}
 if(command.type==='ADD_PREVIOUS_DAY_RANGE'){const prior=dates.filter(d=>d<contextDate).at(-1);if(!prior)throw Error('DATA_UNAVAILABLE');const bs=sessions.get(prior)!;return{overlays:[{id:id(),semanticKey:`previous-day-high:${prior}`,kind:'line',label:'Previous day high',price:Math.max(...bs.map(x=>x.high)),sourceTime:bs.at(-1)!.time},{id:id(),semanticKey:`previous-day-low:${prior}`,kind:'line',label:'Previous day low',price:Math.min(...bs.map(x=>x.low)),sourceTime:bs.at(-1)!.time}],message:`Previous day range resolved from ${prior}`}}
 if(command.type==='ADD_PREVIOUS_WEEK_RANGE'){const d=Temporal.PlainDate.from(contextDate),start=d.subtract({days:d.dayOfWeek+6});const bs=bars.filter(b=>{const x=nyDate(b);return Temporal.PlainDate.compare(x,start)>=0&&Temporal.PlainDate.compare(x,start.add({days:7}))<0});if(!bs.length)throw Error('DATA_UNAVAILABLE');return{overlays:[{id:id(),semanticKey:`previous-week-high:${start}`,kind:'line',label:'Previous week high',price:Math.max(...bs.map(x=>x.high))},{id:id(),semanticKey:`previous-week-low:${start}`,kind:'line',label:'Previous week low',price:Math.min(...bs.map(x=>x.low))}],message:`Previous week range resolved from ${start}`}}
 if(command.type==='ADD_NY_MIDNIGHT_OPEN'){const exact=sessions.get(contextDate)?.find(b=>Temporal.Instant.fromEpochMilliseconds(b.time*1000).toZonedDateTimeISO('America/New_York').hour===0);if(!exact)throw Error('DATA_UNAVAILABLE');return line(`ny-midnight:${contextDate}`,'New York midnight open',exact)}
 if(command.type==='ADD_EMA'){if(bars.length<50)throw Error('DATA_UNAVAILABLE');const points:{time:number;value:number}[]=[];let ema=bars.slice(0,50).reduce((a,b)=>a+b.close,0)/50;points.push({time:bars[49].time,value:ema});for(const b of bars.slice(50)){ema=(b.close-ema)*2/51+ema;points.push({time:b.time,value:ema})}return{overlays:[{id:id(),semanticKey:'ema:50:close',kind:'ema',label:'EMA 50 close',points}],message:`EMA 50 resolved through ${iso(ctx.time)}`}}
 if(command.type==='ADD_HORIZONTAL_LINE')return{overlays:[{id:id(),semanticKey:`user-line:${command.userPrice}:${command.label||''}`,kind:'line',label:command.label||'Horizontal line',price:command.userPrice}],message:`Horizontal line: ${command.userPrice}`};throw Error('Command is handled by the store') }}
